<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['city_name' => 'Bogotá', 'departament_id' => 1],
            ['city_name' => 'Medellín', 'departament_id' => 2],
            ['city_name' => 'Cali', 'departament_id' => 3],
            ['city_name' => 'Barranquilla', 'departament_id' => 4],
            ['city_name' => 'Cartagena', 'departament_id' => 5],
            ['city_name' => 'Santa Marta', 'departament_id' => 6],
            ['city_name' => 'Manizales', 'departament_id' => 7],
            ['city_name' => 'Pereira', 'departament_id' => 8],
            ['city_name' => 'Armenia', 'departament_id' => 9],
            ['city_name' => 'Pasto', 'departament_id' => 10],
            ['city_name' => 'Cúcuta', 'departament_id' => 11],
            ['city_name' => 'Bucaramanga', 'departament_id' => 12],
            ['city_name' => 'Ibagué', 'departament_id' => 13],
            ['city_name' => 'Villavicencio', 'departament_id' => 14],
            ['city_name' => 'Neiva', 'departament_id' => 15],
            ['city_name' => 'Popayán', 'departament_id' => 16],
            ['city_name' => 'Valledupar', 'departament_id' => 17],
            ['city_name' => 'Montería', 'departament_id' => 18],
            ['city_name' => 'Tunja', 'departament_id' => 19],
            ['city_name' => 'Riohacha', 'departament_id' => 20],
            ['city_name' => 'Quibdó', 'departament_id' => 21],
            ['city_name' => 'Silvania', 'departament_id' => 14],
            ['city_name' => 'Tibacuy', 'departament_id' => 14],
            ['city_name' => 'Venecia', 'departament_id' => 14],
            ['city_name' => 'Anapoima', 'departament_id' => 14],
            ['city_name' => 'Anolaima', 'departament_id' => 14],
            ['city_name' => 'Apulo', 'departament_id' => 14],
            ['city_name' => 'Cachipay', 'departament_id' => 14],
            ['city_name' => 'El Colegio', 'departament_id' => 14],
            ['city_name' => 'La Mesa', 'departament_id' => 14],
            ['city_name' => 'Quipile', 'departament_id' => 14],
            ['city_name' => 'San Antonio del Tequendama', 'departament_id' => 14],
            ['city_name' => 'Tena', 'departament_id' => 14],
            ['city_name' => 'Viotá', 'departament_id' => 14],
            ['city_name' => 'Carmen de Carupa', 'departament_id' => 14],
            ['city_name' => 'Cucunubá', 'departament_id' => 14],
            ['city_name' => 'Fúquene', 'departament_id' => 14],
            ['city_name' => 'Ubaté', 'departament_id' => 14],
            ['city_name' => 'Guachetá', 'departament_id' => 14],
            ['city_name' => 'Lenguazaque', 'departament_id' => 14],
            ['city_name' => 'Simijaca', 'departament_id' => 14],
            ['city_name' => 'Susa', 'departament_id' => 14],
            ['city_name' => 'Sutatausa', 'departament_id' => 14],
            ['city_name' => 'Tausa', 'departament_id' => 14],
            ['city_name' => 'Ubaté', 'departament_id' => 14],
            ['city_name' => 'Zipaquirá', 'departament_id' => 14],
        ['city_name' => 'Bojacá', 'departament_id' => 14],
        ['city_name' => 'El Rosal', 'departament_id' => 14],
        ['city_name' => 'Facatativá', 'departament_id' => 14],
        ['city_name' => 'Funza', 'departament_id' => 14],
        ['city_name' => 'Madrid', 'departament_id' => 14],
        ['city_name' => 'Mosquera', 'departament_id' => 14],
        ['city_name' => 'Subachoque', 'departament_id' => 14],
        ['city_name' => 'Zipacón', 'departament_id' => 14],
        ['city_name' => 'Sibaté', 'departament_id' => 14],
        ['city_name' => 'Soacha', 'departament_id' => 14],
        ['city_name' => 'Arbeláez', 'departament_id' => 14],
        ['city_name' => 'Cabrera', 'departament_id' => 14],
        ['city_name' => 'Fusagasugá', 'departament_id' => 14],
        ['city_name' => 'Granada', 'departament_id' => 14],
        ['city_name' => 'Pandi', 'departament_id' => 14],
        ['city_name' => 'Pasca', 'departament_id' => 14],
        ['city_name' => 'San Bernardo', 'departament_id' => 14],
        ['city_name' => 'Quetame', 'departament_id' => 14],
        ['city_name' => 'Ubaque', 'departament_id' => 14],
        ['city_name' => 'Une', 'departament_id' => 14],
        ['city_name' => 'El Peñón', 'departament_id' => 14],
        ['city_name' => 'La Palma', 'departament_id' => 14],
        ['city_name' => 'Pacho', 'departament_id' => 14],
        ['city_name' => 'Paime', 'departament_id' => 14],
        ['city_name' => 'San Cayetano', 'departament_id' => 14],
        ['city_name' => 'Topaipí', 'departament_id' => 14],
        ['city_name' => 'Villagómez', 'departament_id' => 14],
        ['city_name' => 'Yacopí', 'departament_id' => 14],
        ['city_name' => 'Cajicá', 'departament_id' => 14],
        ['city_name' => 'Chía', 'departament_id' => 14],
        ['city_name' => 'Cogua', 'departament_id' => 14],
        ['city_name' => 'Cota', 'departament_id' => 14],
        ['city_name' => 'Gachancipá', 'departament_id' => 14],
        ['city_name' => 'Nemocón', 'departament_id' => 14],
        ['city_name' => 'Sopó', 'departament_id' => 14],
        ['city_name' => 'Tabio', 'departament_id' => 14],
        ['city_name' => 'Tenjo', 'departament_id' => 14],
        ['city_name' => 'Tocancipá', 'departament_id' => 14],
        ['city_name' => 'Bituima', 'departament_id' => 14],
        ['city_name' => 'Chaguaní', 'departament_id' => 14],
        ['city_name' => 'Guayabal de Síquima', 'departament_id' => 14],
        ['city_name' => 'Pulí', 'departament_id' => 14],
        ['city_name' => 'San Juan de Rioseco', 'departament_id' => 14],
        ['city_name' => 'Vianí', 'departament_id' => 14],
        ['city_name' => 'Medina', 'departament_id' => 14],
        ['city_name' => 'Paratebueno', 'departament_id' => 14],
        ['city_name' => 'Cáqueza', 'departament_id' => 14],
        ['city_name' => 'Chipaque', 'departament_id' => 14],
        ['city_name' => 'Choachí', 'departament_id' => 14],
        ['city_name' => 'Fómeque', 'departament_id' => 14],
        ['city_name' => 'Fosca', 'departament_id' => 14],
        ['city_name' => 'Guayabetal', 'departament_id' => 14],
        ['city_name' => 'Gutiérrez', 'departament_id' => 14],
        ['city_name' => 'Caparrapí', 'departament_id' => 14],
        ['city_name' => 'Guaduas', 'departament_id' => 14],
        ['city_name' => 'Puerto Salgar', 'departament_id' => 14],
        ['city_name' => 'Albán', 'departament_id' => 14],
        ['city_name' => 'La Peña', 'departament_id' => 14],
        ['city_name' => 'La Vega', 'departament_id' => 14],
        ['city_name' => 'Nimaima', 'departament_id' => 14],
        ['city_name' => 'Nocaima', 'departament_id' => 14],
        ['city_name' => 'Quebradanegra', 'departament_id' => 14],
        ['city_name' => 'San Francisco', 'departament_id' => 14],
        ['city_name' => 'Sasaima', 'departament_id' => 14],
        ['city_name' => 'Supatá', 'departament_id' => 14],
        ['city_name' => 'Útica', 'departament_id' => 14],
        ['city_name' => 'Vergara', 'departament_id' => 14],
        ['city_name' => 'Villeta', 'departament_id' => 14],
        ['city_name' => 'Gachalá', 'departament_id' => 14],
        ['city_name' => 'Gachetá', 'departament_id' => 14],
        ['city_name' => 'Gama', 'departament_id' => 14],
        ['city_name' => 'Guasca', 'departament_id' => 14],
        ['city_name' => 'Guatavita', 'departament_id' => 14],
        ['city_name' => 'Junín', 'departament_id' => 14],
        ['city_name' => 'La Calera', 'departament_id' => 14],
        ['city_name' => 'Ubalá', 'departament_id' => 14],
        ['city_name' => 'Beltrán', 'departament_id' => 14],
        ['city_name' => 'Chocontá', 'departament_id' => 14],
        ['city_name' => 'Machetá', 'departament_id' => 14],
        ['city_name' => 'Manta', 'departament_id' => 14],
        ['city_name' => 'Sesquilé', 'departament_id' => 14],
        ['city_name' => 'Suesca', 'departament_id' => 14],
        ['city_name' => 'Tibirita', 'departament_id' => 14],
        ['city_name' => 'Villapinzón', 'departament_id' => 14],
        ['city_name' => 'Agua de Dios', 'departament_id' => 14],
        ['city_name' => 'Girardot', 'departament_id' => 14],
        ['city_name' => 'Guataquí', 'departament_id' => 14],
        ['city_name' => 'Jerusalén', 'departament_id' => 14],
        ['city_name' => 'Nariño', 'departament_id' => 14],
        ['city_name' => 'Nilo', 'departament_id' => 14],
        ['city_name' => 'Ricaurte', 'departament_id' => 14],
        ['city_name' => 'Tocaima', 'departament_id' => 14]
        ];
    
        DB::table('cities')->insert($cities);
    }
    }

